extends SceneTree
## Deterministic game-asset import: chroma-key -> RGBA atlases, individual frames,
## per-frame foot/hand anchors and a portable SpriteFrames resource.
## Artwork is generated by imagegen; this compiler never draws character pixels.
## Run: godot --headless --path . --script res://Samples/ArtDirection/Tools/build_character_assets.gd

const DEFAULT_PROFILE := "res://Game/Characters/WhiteSailor/appearance.json"
var completed := false


func _initialize() -> void:
	var path := DEFAULT_PROFILE
	for argument in OS.get_cmdline_user_args():
		if argument.begins_with("profile="):
			path = argument.trim_prefix("profile=")
	build(path)
	quit(0 if completed else 1)


func build(path: String) -> void:
	var profile: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(path))
	var directory := path.get_base_dir()
	var packed_cell := Vector2i(profile.packed_cell_size[0], profile.packed_cell_size[1])
	var registration_path := directory.path_join(profile.registration)
	var registration: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(registration_path))
	var manifest := {"version": 1, "registration_sha256": FileAccess.get_sha256(registration_path), "sheets": {}, "frames": {}}
	var total_frames := 0
	var frame_images: Dictionary = {}
	var frames := SpriteFrames.new()
	frames.remove_animation("default")
	for folder in ["Sheets", "Frames", "Previews"]:
		DirAccess.make_dir_recursive_absolute(directory.path_join(folder))
	for sheet_name: String in profile.sheets:
		var sheet: Dictionary = profile.sheets[sheet_name]
		var cell := _vec_i(sheet.get("cell_size", profile.cell_size))
		var grid := _vec_i(sheet.get("grid", profile.grid))
		assert(registration.sheets[sheet_name].size() == grid.x * grid.y, "Every source frame needs reviewed landmarks")
		var source_path := directory.path_join(sheet.source)
		var source := Image.load_from_file(source_path)
		assert(source != null, "Missing generated source: " + source_path)
		# Image generation may return a different pixel resolution. Landmarks
		# live in an explicit logical source space, independent of that resolution.
		assert(is_equal_approx(float(source.get_width()) / source.get_height(), float(cell.x * grid.x) / (cell.y * grid.y)), "Source aspect ratio must match its declared grid")
		if source.get_size() != cell * grid:
			source.resize(cell.x * grid.x, cell.y * grid.y, Image.INTERPOLATE_NEAREST)
		source.convert(Image.FORMAT_RGBA8)
		# A saturated green key cannot occur in the reference's white/navy/pink
		# palette. Keying is done once on import; runtime uses ordinary alpha PNGs.
		for y in source.get_height():
			for x in source.get_width():
				var pixel := source.get_pixel(x, y)
				if pixel.g > profile.keying.green_min and pixel.g - maxf(pixel.r, pixel.b) > profile.keying.dominance_min:
					source.set_pixel(x, y, Color.TRANSPARENT)
		var groups := _split_figures(source, cell, grid)
		var atlas := Image.create(packed_cell.x * grid.x, packed_cell.y * grid.y, false, Image.FORMAT_RGBA8)
		manifest.sheets[sheet_name] = {"source_sha256": FileAccess.get_sha256(source_path), "texture": sheet.texture}
		var sheet_frames: Array[Dictionary] = []
		for index in grid.x * grid.y:
			var pixels: PackedInt32Array = groups[index]
			assert(pixels.size() > 500, "Missing character: %s/%d" % [sheet_name, index])
			var source_bounds := Rect2i(Vector2i(pixels[0] % source.get_width(), pixels[0] / source.get_width()), Vector2i.ONE)
			for pixel_index in pixels:
				source_bounds = source_bounds.expand(Vector2i(pixel_index % source.get_width(), pixel_index / source.get_width()))
			# Rect2i.expand contains the point inclusively, while a blit rectangle's
			# end is exclusive. Explicit padding protects extreme outline pixels.
			source_bounds.size += Vector2i.ONE
			assert(source_bounds.size.x < packed_cell.x - 8 and source_bounds.size.y < packed_cell.y - 8, "Merged/oversized source figures: %s/%d" % [sheet_name, index])
			var landmarks: Dictionary = registration.sheets[sheet_name][index]
			var origin := Vector2(index % grid.x, index / grid.x) * Vector2(cell)
			var crown := _vec(landmarks.head_axis[0]) + origin
			var chin := _vec(landmarks.head_axis[1]) + origin
			# Scale uses the model's equivalent standing height, never this pose's
			# bounding box or tilted head. This keeps a crouch short and prevents
			# a long sword, bent knee or flipped hair from resizing the body.
			var factor := float(registration.target_model_height) / float(landmarks.size_reference)
			var pelvis := _vec(landmarks.pelvis) + origin
			var support := _vec(landmarks.support) + origin
			var pivot := _vec(registration.packed_pivot)
			var root := Vector2(pelvis.x, support.y)
			if landmarks.mode in ["air", "wall"]:
				# Never root an airborne drawing on its lowest pixel: hair and
				# tucked legs must not push the whole torso up/down. The physics
				# body supplies travel; only the authored small gait bob is baked.
				root.y = pelvis.y + (float(landmarks.get("pelvis_height", registration.pelvis_height)) - float(landmarks.get("bob", 0.0))) / factor
				if landmarks.mode == "wall":
					root.x = support.x
			elif landmarks.mode == "ceiling":
				pivot = _vec(registration.ceiling_pivot)
			var destination := Vector2i((pivot + (Vector2(source_bounds.position) - root) * factor).round())
			var drawing := Image.create(source_bounds.size.x, source_bounds.size.y, false, Image.FORMAT_RGBA8)
			for pixel_index in pixels:
				var point := Vector2i(pixel_index % source.get_width(), pixel_index / source.get_width())
				drawing.set_pixelv(point - source_bounds.position, source.get_pixelv(point))
			drawing.resize(maxi(1, roundi(source_bounds.size.x * factor)), maxi(1, roundi(source_bounds.size.y * factor)), Image.INTERPOLATE_NEAREST)
			assert(destination.x > 0 and destination.y > 0 and destination.x + drawing.get_width() < packed_cell.x and destination.y + drawing.get_height() < packed_cell.y, "Registered figure exceeds frame: %s/%d at %s size %s" % [sheet_name, index, destination, drawing.get_size()])
			var frame := Image.create(packed_cell.x, packed_cell.y, false, Image.FORMAT_RGBA8)
			frame.blit_rect(drawing, Rect2i(Vector2i.ZERO, drawing.get_size()), destination)
			var bounds := frame.get_used_rect()
			var region := Rect2i(Vector2i(index % grid.x, index / grid.x) * packed_cell, packed_cell)
			atlas.blit_rect(frame, Rect2i(Vector2i.ZERO, packed_cell), region.position)
			var frame_path := "Frames/%s_%02d.png" % [sheet_name, index]
			assert(frame.save_png(directory.path_join(frame_path)) == OK)
			frame_images[frame_path] = ImageTexture.create_from_image(frame)
			# Registration is baked into the PNG, not a corrective runtime offset.
			# The portable SpriteFrames and the in-game atlas use identical pixels.
			sheet_frames.append({
				"region": [region.position.x, region.position.y, packed_cell.x, packed_cell.y],
				"bounds": [bounds.position.x, bounds.position.y, bounds.size.x, bounds.size.y],
				"feet": [pivot.x, pivot.y],
				"wall": [pivot.x, pivot.y],
				"ceiling": [pivot.x, pivot.y],
				"registration": {
					"mode": landmarks.mode, "scale": factor,
					"pelvis": _array(pivot + (pelvis - root) * factor),
					"head_axis": [_array(pivot + (crown - root) * factor), _array(pivot + (chin - root) * factor)],
				},
				"path": frame_path,
			})
		manifest.frames[sheet_name] = sheet_frames
		total_frames += sheet_frames.size()
		assert(atlas.save_png(directory.path_join(sheet.texture)) == OK)
	# JSON regions load imported textures at runtime. Standalone SpriteFrames
	# uses embedded ImageTextures so a first build works before Godot's reimport.
	var timings: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(profile.timing_source))
	for extra: Dictionary in profile.get("extra_timing_sources", []):
		var document: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(extra.path))
		var clip: Dictionary = document[extra.key]
		timings[clip.name] = clip
	for name: String in profile.clips:
		var mapping: Dictionary = profile.clips[name]
		var sequence: Dictionary = profile.sequences[mapping.sequence]
		var timing: Dictionary = timings[name]
		frames.add_animation(name)
		frames.set_animation_speed(name, sequence.cells.size() * float(timing.speed) / float(timing.length))
		frames.set_animation_loop(name, timing.loop)
		for key_index in sequence.cells.size():
			var index := int(sequence.cells[key_index])
			var info: Dictionary = manifest.frames[sequence.sheet][index]
			var duration := 1.0
			if mapping.has("frame_times"):
				var next_time := float(mapping.frame_times[key_index + 1]) if key_index + 1 < sequence.cells.size() else 1.0
				duration = (next_time - float(mapping.frame_times[key_index])) * sequence.cells.size()
			frames.add_frame(name, frame_images[info.path], duration)
	assert(ResourceSaver.save(frames, directory.path_join("sprite_frames.res"), ResourceSaver.FLAG_COMPRESS) == OK)
	var file := FileAccess.open(directory.path_join("frame_manifest.json"), FileAccess.WRITE)
	file.store_string(JSON.stringify(manifest, "  ") + "\n")
	completed = true
	print("CHARACTER_ASSETS_PASS sheets=", profile.sheets.size(), " frames=", total_frames, " sequences=", profile.sequences.size())


func _vec(values: Array) -> Vector2:
	return Vector2(values[0], values[1])


func _vec_i(values: Array) -> Vector2i:
	return Vector2i(values[0], values[1])


func _array(value: Vector2) -> Array:
	return [value.x, value.y]


func _split_figures(source: Image, cell: Vector2i, grid: Vector2i) -> Array[PackedInt32Array]:
	# Generated poses can extend over a nominal cell line. Connected silhouettes
	# keep a sword, raised hand or strand of hair with its character instead of
	# cutting them at that line. The component's center assigns its source cell.
	var width := source.get_width()
	var height := source.get_height()
	var data := source.get_data()
	var visited := PackedByteArray()
	visited.resize(width * height)
	var groups: Array[PackedInt32Array] = []
	groups.resize(grid.x * grid.y)
	for start in width * height:
		if visited[start] != 0 or data[start * 4 + 3] == 0:
			continue
		var queue := PackedInt32Array([start])
		visited[start] = 1
		var cursor := 0
		var low := Vector2i(start % width, start / width)
		var high := low
		while cursor < queue.size():
			var current := queue[cursor]
			cursor += 1
			var point := Vector2i(current % width, current / width)
			low = low.min(point)
			high = high.max(point)
			for dy in range(-1, 2):
				for dx in range(-1, 2):
					var neighbor := point + Vector2i(dx, dy)
					if neighbor.x < 0 or neighbor.y < 0 or neighbor.x >= width or neighbor.y >= height:
						continue
					var offset := neighbor.y * width + neighbor.x
					if visited[offset] == 0 and data[offset * 4 + 3] != 0:
						visited[offset] = 1
						queue.append(offset)
		var center := (low + high) / 2
		var column := clampi(center.x / cell.x, 0, grid.x - 1)
		var row := clampi(center.y / cell.y, 0, grid.y - 1)
		groups[row * grid.x + column].append_array(queue)
	return groups
